# Generated by Django 4.2.5 on 2023-10-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
