# Generated by Django 4.2.5 on 2023-10-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageStore', '0003_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
    ]
