# Generated by Django 4.2.5 on 2023-10-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageStore', '0004_rename_producto_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='valoracion',
        ),
    ]
