# Generated by Django 4.2.5 on 2023-10-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManageStore', '0005_remove_productos_valoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('valoracion', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageStore.productos')),
            ],
        ),
    ]
