# Generated by Django 4.2.5 on 2023-10-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageStore', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Productos/'),
        ),
    ]
