# Generated by Django 4.2.5 on 2023-10-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageStore', '0007_alter_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='valoracion',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
